### ISSUE TITLE
Printer and Bar code reader 

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#2]
Which printer and barcode reader works with Sultan? Any brand or Model?

**Comment by apinprastya** [comment]
Any barcode reader will be works.
For printer only work for ESCP/POS printer.

**Comment by shujaatak** [comment]
@apinprastya which barcode reader you use with this software?

**Comment by apinprastya** [comment]
I am using this one : https://www.tokopedia.com/budgetgadget/yongli-barcode-scanner-xyl-8202

**Comment by shujaatak** [comment]
Sultan is an awesome project! 👍

**Comment by shujaatak** [comment]
I have an intent to contribute to this project.

**Comment by apinprastya** [comment]
Thank you.
Anyway, it still in develop (refactoring, change some database tables, etc will still happen a lot) and target to release the first version will be something like beginning of July.
I will be happy if anyone can contribute to the projects.
