### ISSUE TITLE
Error compile on Manjaro Linux

### ISSUE THREAD

**Issue by chokisoklat** [apinprastya/sultan#29]
`suplier/suplierwidget.cpp:63:53: error: invalid use of incomplete type ‘class QHeaderView’
     mTableWidget->getTableView()->horizontalHeader()->setStretchLastSection(true);
![Screenshot_20190420_120453](https://user-images.githubusercontent.com/35197443/56452998-87ef5800-6364-11e9-943e-d4d27f7a7c1c.png)
`

**Comment by apinprastya** [comment]
What Qt version and GCC version do you use?
It happen because the QHeaderView is no more exported on different version. You can fast fix by add
`#include <QHeaderView>` 
at libgui/headerwidget.h
