### ISSUE TITLE
GitHub allows to create releases

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#3]
I find your updates very helpful. But i wonder why you don't create a release before updating the code. It will be much useful for you to track your project and keep copies of the older code in the GitHub!
**The following is the procedure to create releases:**

- Log-in to GitHub 

- Click on **releases**

![image](https://user-images.githubusercontent.com/14161646/27650028-116473c0-5c4d-11e7-9641-c4599be73f54.png)

- In new page you will see all releases you already have created. If found none then the following message will be shown to you:

![image](https://user-images.githubusercontent.com/14161646/27650210-a25adba8-5c4d-11e7-8d81-068ccc701da3.png)

- Now simply click on **Create a new release** In the next page you will be shown the following content:
![image](https://user-images.githubusercontent.com/14161646/27650629-e9f215c0-5c4e-11e7-934d-843c19735a5c.png)

- Now you can give any value to your **Tag Version** like 1.0, 1.1 etc. Optionally you can check **This is a pre-release** and then click on **Publish release**

- Done Enjoy!

**Comment by apinprastya** [comment]
I do understand about the release. The project is not ready for release, there is no point to create any release or tag on github. I have plan to release first version about next month.
Like i said before, the project is still in develop, a lot of changes still happen.
