### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by muxawayah** [apinprastya/sultan#30]
Your code is very complex please tell me in detail how could you send and receive SQLite quarries over the network?
I mean how could you make SQLite support server and client.
sorry for the bad English

**Comment by apinprastya** [comment]
You just joined Github a while a go, this issue portal is for the issue, not for asking.
I will answer your question and close this issue.
It just a basic client and server application, Sultan POS are able to run as server and client at the same time, so the one that make query to SQLite is the server then send it to client over websocket.

**Comment by muxawayah** [comment]
> It just a basic client and server application, Sultan POS are able to run as server and client at the same time, so the one that make query to SQLite is the server then send it to client over websocket.
i know that that
that's why i said "tell me in detail"
how could you make QSqlQuary be sent over the network
