### ISSUE TITLE
Use dot as comma

### ISSUE THREAD

**Issue by astotoster** [apinprastya/sultan#34]
Use dot as comma for typing qty. (because comma key is to far from numeric keypad)

**Comment by apinprastya** [comment]
Koma juga bisa digunakan pada field "Scan barcode" walupun menggunakan pencarian nama. Yaitu contoh membeli gula 1,5 kg. Maka ketikan pada "Scan barcode" : 
1.5*
lalu tekan f2 untuk mencari barang (contoh mencari gula), maka nanti akan terinput gula sebesar 1,5
