### ISSUE TITLE
How can i test it on Raspberry Pi 3 Model B?

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#4]
I tested your image on Raspberry Pi 3 Model B and it failed to boot. I haven't ever used buildroot so can you please mention the method to make a custom image for Raspberry Pi 3 Model B or at least how you came up with your own image for Raspberry Pi?

**Comment by apinprastya** [comment]
Unfortunately, I don't have the device, so I can't help a lot here. I think it should has different image for the device.

**Comment by shujaatak** [comment]
Can you please briefly discuss how you made your own raspberry pi image? Once i know how to make your image then i will make image for Raspberry Pi 3 Model B and post it on your project if you allow.

**Comment by shujaatak** [comment]
External links to the tutorials will also help a lot.

**Comment by apinprastya** [comment]
I think the first thing you can do is to make a build with link i attach above. Just make a simple buildroot with busybox and make it boot to device. After that add package xorg and make it boot and xorg run on device. And finally add Qt. Its a long journey and take times.
Anyway, I have friend that will borrow me Raspberry 3 B+ next week, so probably I will build for it about next week.

**Comment by apinprastya** [comment]
Raspberry Pi 3 image is ready. Will be released in couple hours from now.

**Comment by shujaatak** [comment]
I am waiting for it.

**Comment by apinprastya** [comment]
@shujaatak : I think you are the only one who wait Sultan released. :)
It take sometimes to upload on my side, I don't have a good internet connection here.

**Comment by shujaatak** [comment]
WoW! I tested the Raspberry Pi image and it works GREAT! 
BIG THANK YOU!
By the way, I think there would be many who are silently waiting for Sultan releases.

**Comment by shujaatak** [comment]
I am still really struggling with buildroot :( 
Can you please write down the steps to make an image for raspberry pi using buildroot please?
I tried to build using these commands:
```
$ wget https://buildroot.org/downloads/buildroot-2017.02.4.tar.bz2
$ tar xvjf buildroot-2017.02.4.tar.bz2
$ cd buildroot-2017.02.4
$ make help
$ make list-defconfigs
$ make raspberrypi3_defconfig
$ make all
```
Everything goes well until `make all`. The script downloads around 2GB data from internet and hangs after about an hour. I also don't know how to integrate Qt.

**Comment by apinprastya** [comment]
Please read the manual : [Buildroot Manual](https://buildroot.org/downloads/manual/manual.html)
And there are a lot of tutorial about buildroot out there. You have to learn it little by little. I have to learn it about a week to make Sultan able to run on Raspberry. You just need time to understand it.
Someone write his tutorial here : [Raspberry Buildroot](https://github.com/pbouda/buildroot-qt-dev)

**Comment by shujaatak** [comment]
I have read the manual and i also have followed the instructions mentioned [here](https://github.com/gamaral/rpi-buildroot) but without any success :(
