### ISSUE TITLE
Solds item number

### ISSUE THREAD

**Issue by idhamperdameian** [apinprastya/sultan#46]
Solds item number can have more than one, it shoud be unique. Right?

![Capture](https://user-images.githubusercontent.com/3077042/69493735-f0974800-0ee4-11ea-97bd-b58f83e4cd75.PNG)

**Comment by apinprastya** [comment]
Please run select * from solds where number = ‘CS1-190521031’

**Comment by idhamperdameian** [comment]
> Please run select * from solds where number = ‘CS1-190521031’

Here is this
![Capture2](https://user-images.githubusercontent.com/3077042/69494341-27715c00-0eed-11ea-83c2-4741e515f215.PNG)

**Comment by idhamperdameian** [comment]
May i suggest you change the code in line https://github.com/apinprastya/sultan/blob/7a91c0fbb35b434af902bd8ed79fe0d8dcc64984/libglobal/util.cpp#L128
to this

>  const QString &time = QDateTime::currentDateTime().toString("hhmmss");
> const QString &ret = QString("%1-%2%3%4").arg(name).arg(now).arg(QString(val).rightJustified(3, '0')).arg(time);`

the last argument in line `.arg(val, 3, 16, QChar('0'))` may have unexpected value so need to change to `.arg(QString(val).rightJustified(3, '0'))`

![Capture](https://user-images.githubusercontent.com/3077042/69496112-1fbbb280-0f01-11ea-97f0-fe347a264ecb.PNG)
---
[QRandomGenerator Class](https://doc.qt.io/qt-5/qrandomgenerator.html) is another choice i think

**Comment by apinprastya** [comment]
The last abcd number is expected behavior as it is a 16based number and why this is 16based number because in three digit it will generate more number then a 10based number.
And regarding the number code changes, I think you can send a PR by using new number generator but with adding flag to the setting, so there is will be a new setting entry called "Add time to sold number" as a boolean checkbox.

And for the number duplication seems I will check later next week, but I am open if you send me the PR of the fix

**Comment by idhamperdameian** [comment]
Since random number is not affected to end user and previous transaction, i think no need to adding new flag to setting. If you agree i will send PR base on what i suggest before.

About duplicate number in database i think no future action can we do as just leave it since the customer have print of transaction.

**Comment by apinprastya** [comment]
Yes I think it is not a problem, the only problem is the length of it. Because when it is too long, it will not properly fit on the receipt

**Comment by idhamperdameian** [comment]
Yes you'r right. How about this 
```cpp
const QString &ret = QString("%1-%2%3%4%5").arg(name).arg(now).arg(QString(val).rightJustified(2, '0')).arg(QRandomGenerator::global()->bounded(99)).arg(QDateTime::currentDateTime().toString("s"));
```

Possible output is `CS1-191126012310` with length 16 char. Previous number is  `CS1-19111001c` with length 13 char. 

---
Or totally different with previous one like this:

```cpp
const QString &ret = QString("%1-%2%3%4").arg(name).arg(QRandomGenerator::global()->bounded(100, 999)).arg(QDate::currentDate().dayOfYear()).arg(QDateTime::currentDateTime().toString("hms"));
```

Possible output is `CS1-100365201818` with length 16 char.

I love the last number generator, it will be more unique. It depend on `QRandomGenerator` in one second to create unique number.

If we use new number it would take place on yellow horizontal line.

![2725aa4a-c264-4a44-a17f-b5eccd53ba1e](https://user-images.githubusercontent.com/3077042/69601791-f8bbc880-1047-11ea-9d60-12edde8c7d38.jpg)

**Comment by apinprastya** [comment]
Sorry for the late reply, actually I prefer if we can fix about why the same number can be appear on multiple records. I didn't check yet about why this issue could happen.
And regarding the number generation, after checking with some friends (the SultanPOS users) and they said like the number in order, so they can easily check how many sale invoices today.
So I think what we can do is : fix about the duplication number and also change the 16based number to as you proposed `.arg(QString(val).rightJustified(3, '0'))`

**Comment by idhamperdameian** [comment]
Hi, I think method `QString Util::genSoldNumber()` is good, no need to change https://github.com/apinprastya/sultan/blob/7a91c0fbb35b434af902bd8ed79fe0d8dcc64984/libglobal/util.cpp#L111 
I just test the code below to make sure:

```cpp
QMap<QString, int> map;
QString val;

for(int i = 0; i < 90000; i++) {
    val = QString("%1").arg(i, 3, 16, QChar('0'));
    map.insert(val, map.value(val, 0) + 1);
}

QMapIterator<QString, int> i(map);
while (i.hasNext()) {
    i.next();
    if (i.value() > 1)
    qDebug() << i.key() << ": " << i.value() << endl;
}
```

The result is great, no duplicate number.

### `Why the same number can be appear on multiple records?`

I'm not sure what happened, i'll check it later

**Comment by apinprastya** [comment]
I don't think that 90000 is way too big, I believe 1000 transactions a day is hard to achieve. And if the shop has 1000 transactions a day, they have no reason of using SultanPOS. They will chose the paid POS.
As my main purpose of create this POS is to help the small warung or very beginning of minimarket.
Regarding the duplicate number, do you use more than cashier? When I check on the code, the possibility that number duplicated is from different machine.

**Comment by idhamperdameian** [comment]
About 90000 is only to make me sure about the number generator because I not familiar with c++ before :sweat_smile:

I believe and sure there is only one machine. I asking them about the machine that use SultanPOS, are they using software like deep freeze and they said no.

Sure this is confusing me.
