### ISSUE TITLE
Tidak bisa jalan di openSUSE Leap 15.2

### ISSUE THREAD

**Issue by xakiy** [apinprastya/sultan#52]
Saya coba jalankan Sultan 64bit 20.02.01 AppImage di openSUSE Tumbleweed bisa berjalan lancar, tapi tidak di openSUSE Leap 15.2,  ada clue untuk debug, soalnya tidak ada debug output meski sudah saya extract dan dijalankan lewat cli?

**Comment by cho2** [comment]
Dicoba juga di openSUSE 15.2

- Jalankan dengan perintah `./Sultan_Linux-x86_64.AppImage`, tidak ada respon
- Ekstrak `/Sultan_Linux-x86_64.AppImage --appimage-extract` dan jalankan `./Sultan` dari direktori hasil ekstrak `squashfs-root/usr/bin `, tidak ada respon juga

**Comment by apinprastya** [comment]
Halo, masalah utama sebenernya ada di opensslnya, Qt bawaan yang di bundling menjadi AppImage dicompile menggunakan openssl 1.0, sedangkan rata2 GNU/Linux yang keluaran baru2 ini pakainya openssl 1.1.
Sedang mencari cara bagaimana caranya untuk sekalian bundling openssl yang 1.0 ke AppImagenya.

**Comment by xakiy** [comment]
Iya bener mas, akhirnya kemarin jalan jg setelah nemu log di folder .sultan, semacam ssl error, sy install semua openssl akhirnya jalan..

Aplikasinya bagus, thanks, keep it up :+1:
