### ISSUE TITLE
Tolong dibuatkan fitur koperasi

### ISSUE THREAD

**Issue by andrikaryadi** [apinprastya/sultan#54]
Tolong dibuatkan fitur koperasi, karena UMKM sekarang banyak yang lahir dari koperasi.
jika ada fitur koperasi pasti akan sangat membantu ukm berbasis koperasi, fiturnya seperti 
1. iuran anggota
2. penjualan ke anggota berbeda harganya dengan penjualan ke umum
3. member anggota
4. perhitungan hasil SHU
5. keuntungan koperasi
5. pelaporannya

Terima kasih

**Comment by apinprastya** [comment]
Untuk saat ini fitur ini tidak memungkinkan untuk saya implement karena melebar dari POS.
