### ISSUE TITLE
Pencarian item di kasir 2in1

### ISSUE THREAD

**Issue by Akakz** [apinprastya/sultan#55]
Pencarian item di kasir bisa cari nama barang dan barcode sekaligus,..  2 in 1 tanpa ubah2 dipengaturan...

**Comment by apinprastya** [comment]
Terima kasih untuk sarannya. Boleh tahu ini untuk kasusnya dilapangan seperti apa ya? karena kalau mode barcode tetep bisa cari nama barang dengan menekan F2.

**Comment by Akakz** [comment]
kasus seperti ini, sepatu sendal mainan, biasanya tidak ada barcode, jadi
di input menggunakan kode item, misal kode item 12345 nama item sepatu
hello kitty.. biasanya di toko di tempel 12345 menggunakan cetak label
biasa... jadi kalau bisa menu pencariannya bisa cari nama dan code
sekaligus,  atau di buat 2 kolom ada kolom cari kode ada cari nama

Pada tanggal Kam, 29 Apr 2021 11.24, Muchamad Arifin Dwi P <
***@***.***> menulis:

**Comment by Akakz** [comment]
oh, maaf pak, ternyata bisa ya.. pakai mode barcode ya, jgn mode cari
nama.. mohon maaf sebelumnya.. thx ya...

Pada tanggal Kam, 29 Apr 2021 11.56, Adrianus Akak ***@***.***>
menulis:
