### ISSUE TITLE
Mode Transaksi kasir super cepat

### ISSUE THREAD

**Issue by Akakz** [apinprastya/sultan#56]
bisakah saat kolom scan barcode tidak terisi karakter apapun saat menekan enter adalah bayar... kasus seperti ini, ada yg beli eskrim  1 bh uang pas, jadi dari kasir cukup scan enter enter enter,....  sebab untuk toko dekat sekolahan, transaksi seperti ini sangat sering, jadi cukup scan enter enter enter... terima kasih sebelumnnya...

**Comment by astotoster** [comment]
> bisakah saat kolom scan barcode tidak terisi karakter apapun saat menekan enter adalah bayar... kasus seperti ini, ada yg beli eskrim 1 bh uang pas, jadi dari kasir cukup scan enter enter enter,.... sebab untuk toko dekat sekolahan, transaksi seperti ini sangat sering, jadi cukup scan enter enter enter... terima kasih sebelumnnya...

setuju, tombol enter sebagai alternatif tombok f4

**Comment by apinprastya** [comment]
sudah ter implementasi
