### ISSUE TITLE
Lost MySQL Database Connection

### ISSUE THREAD

**Issue by bukanspot** [apinprastya/sultan#58]
Saya mencoba untuk menggunakan koneksi database **MySQL** dari hosting, tetapi terjadi masalah yaitu koneksi sering lost akibatnya sering tidak bisa melakukan transaksi _(item tidak ditemukan)_ padahal saya cek menggunakan **RDBMS** koneksi ke database tidak ada masalah. 

I tried to use the MySQL database connection from the hosting, but there was a problem that the connection was often lost as a result, I often couldn't make transactions (items not found) even though I checked using an RDBMS, the connection to the database was no problem. (translate)

@apinprastya

**Comment by apinprastya** [comment]
Boleh di screen shoot mas pas error koneksinya?

**Comment by bukanspot** [comment]
Kemarin itu saya menggunakan database mysql yang dihosting, (niatnya agar database bisa diakses dari mana saja) dan dibuatkan interface web untuk melihat data penjualan. Tapi kendalanya sering lost koneksi, dibeberapa situasi harus menunggu lama ketika input data barang dan hal lain yang berhubungan dengan database. Entah masalahnya pada koneksi host database saya atau dari aplikasi sultan, untuk penggunaan database mysql lokal sih aman dan untuk penggunaan database yang dihost di aplikasi lain juga aman.

Note. 
- Saya sudah tidak menggunakan sultan dan isu ini saya buat beberapa tahun lalu, bisa saja sudah solve di versi sekarang.
- Saya sudah tidak ada akses ke database yang dihosting, jadi saya tidak bisa test lagi untuk kondisi sekarang.

**Comment by apinprastya** [comment]
oke makasih saya tutup kalau begitu issue nya
