### ISSUE TITLE
Tidak bisa jalan di Pop!_OS 20.04 LTS

### ISSUE THREAD

**Issue by dianariyanto** [apinprastya/sultan#61]
Lapor lek, Sultan_Linux-x86-64.AppImage tidak bisa berjalan di Pop!_OS 20.04 LTS 64-bit tidak muncul tampilan dan tidak ada notif apa - apa. Terimakasih.

**Comment by apinprastya** [comment]
Untuk saat ini memang belum bisa untuk sistem operasi yang baru2.

**Comment by dianariyanto** [comment]
Support untuk keluarga debian versi berapa ya? atau hanya untuk platform ARM saja kah @apinprastya ?
