### ISSUE TITLE
Installer untuk sistem operasi Armbian Linux ARM64

### ISSUE THREAD

**Issue by dianariyanto** [apinprastya/sultan#67]
Apakah kedepannya akan tersedia installer untuk sistem operasi Armbian Linux ARM64? mengingat saat ini banyak perangkat murah dan hemat daya yang bisa menjalankan Armbian Linux. Jika tidak, akankah disediakan dokumentasi untuk menjalankan aplikasi ini di Armbian/Os berbasis linux ARM64?

Terimakasih banyak.

**Comment by apinprastya** [comment]
Belum ada mas untuk yang Arm64. Apakah pakai yang installer versi raspbian enggak bisa?

**Comment by dianariyanto** [comment]
> Belum ada mas untuk yang Arm64. Apakah pakai yang installer versi raspbian enggak bisa?

Ternyata bisa menggunakan installer versi raspbian, terimakasih banyak.
