### ISSUE TITLE
Qt Version

### ISSUE THREAD

**Issue by araneta** [apinprastya/sultan#73]
Gan ini klo di Windows perlu Qt versi berapa? q coba compile pake Qt 5.5 ga bisa. padahal di wikinya just use Qt 5.5 for easier.

**Comment by apinprastya** [comment]
Iya pakai itu harusnya gan. Pakai 5.9 juga bisa harusnya. Kalau ada error mungkin bisa di taruh disini errornya apa biar bisa bantu.

**Comment by araneta** [comment]
pake Qt 5.5.1 
20:48:11: Running steps for project sultan...
20:48:11: Configuration unchanged, skipping qmake step.
20:48:11: Starting: "C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe" 
	cd external_library\pillow\pillowcore\ && ( if not exist Makefile C:\Qt\Qt5.5.1\5.5\msvc2012\bin\qmake.exe C:\Users\Asus\Documents\projects\sultan-master\sultan-master\external_library\pillow\pillowcore\pillowcore.pro -spec win32-msvc2012 "CONFIG+=debug" -o Makefile ) && C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cd libglobal\ && ( if not exist Makefile C:\Qt\Qt5.5.1\5.5\msvc2012\bin\qmake.exe C:\Users\Asus\Documents\projects\sultan-master\sultan-master\libglobal\libglobal.pro -spec win32-msvc2012 "CONFIG+=debug" -o Makefile ) && C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cd libdb\ && ( if not exist Makefile C:\Qt\Qt5.5.1\5.5\msvc2012\bin\qmake.exe C:\Users\Asus\Documents\projects\sultan-master\sultan-master\libdb\libdb.pro -spec win32-msvc2012 "CONFIG+=debug" -o Makefile ) && C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cl -c -nologo -Zc:wchar_t -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -EHsc /Fd..\bin\db.pdb -DUNICODE -DWIN32 -DDB_LIBRARY -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\..\sultan-master\libdb -I. -I..\..\sultan-master\libglobal -IC:\Qt\Qt5.5.1\5.5\msvc2012\include -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtGui -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtANGLE -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtSql -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtConcurrent -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtCore -Idebug -IC:\Qt\Qt5.5.1\5.5\msvc2012\mkspecs\win32-msvc2012 -Fodebug\ @C:\Users\Asus\AppData\Local\Temp\db.obj.18112.0.jom
db.cpp
	cl -c -nologo -Zc:wchar_t -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -EHsc /Fd..\bin\db.pdb -DUNICODE -DWIN32 -DDB_LIBRARY -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\..\sultan-master\libdb -I. -I..\..\sultan-master\libglobal -IC:\Qt\Qt5.5.1\5.5\msvc2012\include -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtGui -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtANGLE -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtSql -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtConcurrent -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtCore -Idebug -IC:\Qt\Qt5.5.1\5.5\msvc2012\mkspecs\win32-msvc2012 -Fodebug\ @C:\Users\Asus\AppData\Local\Temp\dbutil.obj.18112.16.jom
dbutil.cpp
..\..\sultan-master\libdb\dbutil.cpp(28) : error C2470: 'format' : looks like a function definition, but there is no parameter list; skipping apparent body
..\..\sultan-master\libdb\dbutil.cpp(42) : error C2065: 'format' : undeclared identifier
..\..\sultan-master\libdb\dbutil.cpp(42) : error C3312: no callable 'begin' function found for type ''unknown-type''
..\..\sultan-master\libdb\dbutil.cpp(42) : error C3312: no callable 'end' function found for type ''unknown-type''
..\..\sultan-master\libdb\dbutil.cpp(43) : error C2065: 's' : undeclared identifier
..\..\sultan-master\libdb\dbutil.cpp(44) : error C3536: 'date': cannot be used before it is initialized
..\..\sultan-master\libdb\dbutil.cpp(44) : error C2228: left of '.isValid' must have class/struct/union
        type is 'int'
..\..\sultan-master\libdb\dbutil.cpp(45) : error C3536: 'date': cannot be used before it is initialized
..\..\sultan-master\libdb\dbutil.cpp(45) : error C2664: 'QDate::QDate(const QDate &)' : cannot convert parameter 1 from 'int' to 'const QDate &'
        Reason: cannot convert from 'int' to 'const QDate'
        Constructor for class 'QDate' is declared 'explicit'
..\..\sultan-master\libdb\dbutil.cpp(51) : error C2065: 'format' : undeclared identifier
..\..\sultan-master\libdb\dbutil.cpp(51) : error C3312: no callable 'begin' function found for type ''unknown-type''
..\..\sultan-master\libdb\dbutil.cpp(51) : error C3312: no callable 'end' function found for type ''unknown-type''
..\..\sultan-master\libdb\dbutil.cpp(52) : error C2065: 's' : undeclared identifier
..\..\sultan-master\libdb\dbutil.cpp(53) : error C3536: 'date': cannot be used before it is initialized
..\..\sultan-master\libdb\dbutil.cpp(53) : error C2228: left of '.isValid' must have class/struct/union
        type is 'int'
..\..\sultan-master\libdb\dbutil.cpp(54) : error C3536: 'date': cannot be used before it is initialized
..\..\sultan-master\libdb\dbutil.cpp(54) : error C2664: 'QDateTime::QDateTime(const QDateTime &)' : cannot convert parameter 1 from 'int' to 'const QDateTime &'
        Reason: cannot convert from 'int' to 'const QDateTime'
        No constructor could take the source type, or constructor overload resolution was ambiguous
	cl -c -nologo -Zc:wchar_t -Zi -MDd -GR -W3 -w34100 -w34189 -w44996 -EHsc /Fd..\bin\db.pdb -DUNICODE -DWIN32 -DDB_LIBRARY -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\..\sultan-master\libdb -I. -I..\..\sultan-master\libglobal -IC:\Qt\Qt5.5.1\5.5\msvc2012\include -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtGui -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtANGLE -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtSql -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtConcurrent -IC:\Qt\Qt5.5.1\5.5\msvc2012\include\QtCore -Idebug -IC:\Qt\Qt5.5.1\5.5\msvc2012\mkspecs\win32-msvc2012 -Fodebug\ @C:\Users\Asus\AppData\Local\Temp\migration.obj.18112.31.jom
migration.cpp
c:\users\asus\documents\projects\sultan-master\sultan-master\libdb\migration.h(44) : error C2864: 'LibDB::Migration::mAfterMigrate' : only static const integral data members can be initialized within a class
..\..\sultan-master\libdb\migration.cpp(27) : error C2470: 'TAG' : looks like a function definition, but there is no parameter list; skipping apparent body
..\..\sultan-master\libdb\migration.cpp(105) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\migration.cpp(114) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\migration.cpp(122) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(35) : error C2470: 'TAG' : looks like a function definition, but there is no parameter list; skipping apparent body
..\..\sultan-master\libdb\db.cpp(38) : error C2470: 'SQLDRIVERNAME' : looks like a function definition, but there is no parameter list; skipping apparent body
..\..\sultan-master\libdb\db.cpp(63) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(228) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(280) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(282) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(283) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(309) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(312) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(313) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(341) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(344) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(345) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(362) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(365) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(366) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(413) : error C2065: 'SQLDRIVERNAME' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(414) : error C3536: 'database': cannot be used before it is initialized
..\..\sultan-master\libdb\db.cpp(414) : error C2664: 'QThreadStorage<T>::setLocalData' : cannot convert parameter 1 from 'int' to 'QSqlDatabase'
        with
        [
            T=QSqlDatabase
        ]
        No constructor could take the source type, or constructor overload resolution was ambiguous
..\..\sultan-master\libdb\db.cpp(415) : error C3536: 'database': cannot be used before it is initialized
..\..\sultan-master\libdb\db.cpp(415) : error C2664: 'QSqlDatabase::QSqlDatabase(const QSqlDatabase &)' : cannot convert parameter 1 from 'int' to 'const QSqlDatabase &'
        Reason: cannot convert from 'int' to 'const QSqlDatabase'
        No constructor could take the source type, or constructor overload resolution was ambiguous
..\..\sultan-master\libdb\db.cpp(463) : error C2065: 'TAG' : undeclared identifier
..\..\sultan-master\libdb\db.cpp(467) : error C2065: 'TAG' : undeclared identifier
jom: C:\Users\Asus\Documents\projects\sultan-master\build-sultan-Desktop_Qt_5_5_1_MSVC2012_32bit-Debug\libdb\Makefile.Debug [debug\db.obj] Error 2
jom: C:\Users\Asus\Documents\projects\sultan-master\build-sultan-Desktop_Qt_5_5_1_MSVC2012_32bit-Debug\libdb\Makefile.Debug [debug\dbutil.obj] Error 2
jom: C:\Users\Asus\Documents\projects\sultan-master\build-sultan-Desktop_Qt_5_5_1_MSVC2012_32bit-Debug\libdb\Makefile.Debug [debug\migration.obj] Error 2
jom: C:\Users\Asus\Documents\projects\sultan-master\build-sultan-Desktop_Qt_5_5_1_MSVC2012_32bit-Debug\libdb\Makefile [debug] Error 2
jom: C:\Users\Asus\Documents\projects\sultan-master\build-sultan-Desktop_Qt_5_5_1_MSVC2012_32bit-Debug\Makefile [sub-libdb-make_first-ordered] Error 2
20:48:15: The process "C:\Qt\Qt5.5.1\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project sultan (kit: Desktop Qt 5.5.1 MSVC2012 32bit)
When executing step "Make"
20:48:15: Elapsed time: 00:04.

**Comment by apinprastya** [comment]
Ini masalah di compiler sih kemungkinan, coba install yang Qt MinGW

**Comment by apinprastya** [comment]
Pakai Qt yang MinGW
