### ISSUE TITLE
Again Sultan is not compiling on Windows

### ISSUE THREAD

**Issue by shujaatak** [apinprastya/sultan#8]
I am using Qt5.9.1 MSVC and webenginewidgets.
When compiling i get these errors:

- mainwindow.obj:- 1: error: LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl LibG::AbstractSultanGUI::~AbstractSultanGUI(void)" (__imp_??1AbstractSultanGUI@LibG@@UEAA@XZ) referenced in function "int `public: __cdecl LibGUI::MainWindow::MainWindow(class LibG::MessageBus *,class QWidget *)'::`1'::dtor$2" (?dtor$2@?0???0MainWindow@LibGUI@@QEAA@PEAVMessageBus@LibG@@PEAVQWidget@@@Z@4HA)
File not found mainwindow.obj

- mainwindow.obj:- 1: error: LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl LibG::AbstractSultanGUI::AbstractSultanGUI(void)" (__imp_??0AbstractSultanGUI@LibG@@QEAA@XZ) referenced in function "public: __cdecl LibGUI::MainWindow::MainWindow(class LibG::MessageBus *,class QWidget *)" (??0MainWindow@LibGUI@@QEAA@PEAVMessageBus@LibG@@PEAVQWidget@@@Z) 
File not found mainwindow.obj

- ..\bin\gui.dll:- 1: error: LNK1120: 2 unresolved externals

**Comment by shujaatak** [comment]
I can see there is no gui.dll file in bin directory.

**Comment by apinprastya** [comment]
This could be related to compiler. Everything fine using GCC and LVVM.
There is no gui.dll because it fail when compiling.

**Comment by shujaatak** [comment]
Now it's working! Fantastic!
