### ISSUE TITLE
apakah menggunakan windeployqt untuk membuat file ditribusi portabel ?

### ISSUE THREAD

**Issue by masmanto** [apinprastya/sultan#82]
saya bekerja dengan windows, saya mencoba membuat file distribusi **windeployqt** dengan perintah paling sederhana 

```
windeployqt Sultan.exe

```
tanpa opsi apapun.

tetapi dengan cara ini beberapa library tidak berhasil disertakan seperti printsupport, sqldrivers dan lainnya. 

Jika iya, Tolong buatkan perintah lengkapnya dan buat dalam file.bat 
Jika tidak, bagaimana alternatif lain selain dengan **windeployqt**.

**Comment by apinprastya** [comment]
Tinggal download release Sultan POS yang ada aja, terus nanti hasil compile Sultan yang baru Sultan.exe dan dll nya di taruh di folder release Sultan POS.

**Comment by kangmanto** [comment]
terima kasih,.. 
saya telah melakukan itu sebelumnya, dan berjalan dengan baik.
saya ingin memastikan yang saya lakukan bukan salah.

**Comment by apinprastya** [comment]
ok terima kasih sudah benar seperti itu. saya tutup issuenya
