### ISSUE TITLE
Tambah Fitur total jumlah item yang dibeli

### ISSUE THREAD

**Issue by zetachenk11** [apinprastya/sultan#84]
mas apin..bisa minta di tambah lagi untuk cetak struknya itu ada keterangan jumlah total semua item yang dibeli di kolom bawah..jadi biar bisa cek untuk inputan sama jumlah barang realnya.
![struk](https://github.com/apinprastya/sultan/assets/134042797/d2a74f6c-1d03-42f1-966e-a7d48a417669)
seperti itu mas contohnya. Terimakasih

**Comment by apinprastya** [comment]
Jenis item enggak butuh kah? Kalau contoh di atas brarti jenis item ada 2

**Comment by zetachenk11** [comment]
ngga butuh mas..cuma total semuanya aja

**Comment by zetachenk11** [comment]
gmn mas apin..untuk keterangana total qty penjualannya apakah bisa?

**Comment by apinprastya** [comment]
Bisa mas, tapi harus sabar nunggu next release
