### ISSUE TITLE
Make multi prices issue on cashier as a feature

### ISSUE THREAD

**Issue by astotoster** [apinprastya/sultan#85]
Mas bisa "imulti prices issue o cashier" dijadikan fitur saja?

Versi sebelumnya kalau ada item yang qty nya dirubah ke multi price (misal 12), trus dibalikin ke qty lebih rendah (misal 1), harganya masih ikut ke harga multi prices.
Nah issue itu sering aku pake buat ngasih harga potongan ke kustemer tertentu yang mau dijual lagi. Misal pengecer/warung beli rokok 1 pack atau 3 pack kalau dijual lagi, aku kasih harga potongan.

Atau mungkin ada solusi lain untuk ngasih harga potongan?

**Comment by apinprastya** [comment]
Silakan request fitur baru saja mending mas. Request fitur untuk multiprice with level. Jadi nanti untuk tiap customer bisa beda harga.
Issue ini aku tutup silakan buka issue baru untuk request fitur harga per pelanggan.

**Comment by astotoster** [comment]
ok siap
