### ISSUE TITLE
 transaksi pembelian yang jatuh tempo atau hutang 

### ISSUE THREAD

**Issue by anggrek1** [apinprastya/sultan#86]
transaksi pembelian yang jatuh tempo atau hutang agar bisa kita cicil dalam pembayaran, tidak langsung lunas 
Misalnya dalam Pembelian jumlah besar sales atau penjual memberikan kesempatan kita untuk melunaskan secara bertahap

**Comment by astotoster** [comment]
Pada update versi terbaru "Fix issue payment still works with payment less then the total sale", seharusnya ada option "yes or no". Jadi kalau pilih Yes mungkin bisa masuk ke pilih daftar pelanggan / data piutang pelanggan.

**Comment by apinprastya** [comment]
@astotoster untuk yang pembayaran penjualan harusnya kalau sudah scan pelanggan bakalan bisa pembayaran kurang dari total nya. Kalau tanpa pelanggan pembayaran kurang dari total akan selalu error.
